apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mainorg-vaultk8s-job
  namespace: mainorg-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mainorg-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    nameOverride: mainorg-vaultk8s-job
    global:
      serviceAccountName: vault-auth
      cluster:
        cloudNativeServices: false
        kubernetesUrl: https://B4E7F4769EEF1A6ECB376C2D47B30DFD.gr7.eu-west-1.eks.amazonaws.com
      vault:
        type: hashicorp
        role: vault-role
        address: http://ec2-3-254-84-201.eu-west-1.compute.amazonaws.com:8200
        authPath: devmainorg
        network: fabric
        secretEngine: secretsv2
        secretPrefix: "data/mainorg"
        tls:
    image:
      repository: ghcr.io/hyperledger/bevel-alpine
      tag: latest
      pullSecret: "regcred"
